@startuml
' use strict UML mode
skinparam style strictuml

actor "User" as user

participant "Administration" as main <<main>>
main++

create "productMainMenu" as menu <<frame>>
main -> menu : construct
main -> menu++ : setVisible(true)

user -> menu++ : click 'Add a New Product'

create "ProductDialog" as editor <<dialog>>
menu -> editor : construct

'activate editor constructor
editor++

' create a DAO
create "PrductList" as dao <<DAO>>
editor -> dao : construct

menu -> editor++ : setVisible(true)



' user enters product details and clicks the save button
user -> editor++ : enters product details
editor--
user -> editor++ : clicks save button

' construct the product object
create "Product : product" as product <<domain>>
editor -> product : construct


' get the details from the text component
editor -> editor : get details entered by user


' set the id field in the product
editor -> product++ : set fields
product--

' save product
editor -> dao++ : addProduct(product)
dao--

'display categories
editor -> dao++ : getCategories()
dao--

create "SimpleListModel" as model <<model>>
editor -> model : construct
editor -> model++ :updateItems(dao)
model--
editor -> editor : setModel(model)



' dispose dialog
editor -> editor-- : dispose()

' show control returning to the menu as the dialog closes
return

destroy editor

menu –> user-- : ready for next operation
@enduml