@startuml
' use strict UML mode
skinparam style strictuml

actor "User" as user

participant "ViewProductDialog" as editor <<dialog>>
user -> editor++ : enter an ID and click 'Search'

editor -> editor: getText():id

create "PrductList" as dao <<DAO>>

create "ProductDao" as interface <<interface>> 
dao -> interface : implement


editor -> interface : construct
editor -> interface++ : findProduct(id)
dao++

interface--
dao--

create "SimpleListModel" as model <<model>>
editor -> model : construct

editor -> model++ : updateItems(dao)
model--


editor –> user-- : ready for next operation
@enduml
